server:
  port: 8080

spring:
  application:
    name: task-manager

db:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

assistant:
  api-key: ${ASSISTANT_API_KEY}